# Generated by Django 5.2.17 on 2026-09-25 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(db_index=True, default=100, help_text='越小越优先。')),
                ('enabled', models.BooleanField(default=True)),
                ('match_field', models.CharField(choices=[('subject', '主题'), ('from', '发件人'), ('to', '收件人'), ('body', '正文')], max_length=20)),
                ('match_op', models.CharField(choices=[('contains', '包含'), ('regex', '正则'), ('equals', '等于'), ('domain', '域名')], max_length=20)),
                ('match_value', models.CharField(max_length=500)),
                ('action_type', models.CharField(choices=[('assign_group', '分配到组'), ('assign_user', '分配到人'), ('add_tag', '打标签'), ('set_status', '设置状态')], max_length=20)),
                ('action_value', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mailbox', models.ForeignKey(help_text='该规则只对指定入口邮箱生效。', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='accounts.mailbox')),
            ],
            options={
                'verbose_name': '路由规则',
                'verbose_name_plural': '路由规则',
                'db_table': 'rules',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', '全局'), ('group', '组覆盖')], max_length=20)),
                ('body', models.TextField(help_text='支持 {{ ticket_id }} 等变量。')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, help_text='scope=group 时使用。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='accounts.group')),
            ],
            options={
                'verbose_name': '自动回复模板',
                'verbose_name_plural': '自动回复模板',
                'db_table': 'templates',
                'constraints': [models.UniqueConstraint(fields=('scope', 'group'), name='unique_template_per_scope')],
            },
        ),
    ]
