# Generated by Django 5.2.17 on 2026-09-25 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=500)),
                ('in_reply_to', models.CharField(blank=True, max_length=500)),
                ('references', models.TextField(blank=True)),
                ('direction', models.CharField(choices=[('in', '收信'), ('out', '发信')], max_length=10)),
                ('type', models.CharField(choices=[('message', '邮件'), ('note', '内部备注')], default='message', max_length=10)),
                ('from_addr', models.EmailField(blank=True, max_length=254)),
                ('to_addr', models.TextField(blank=True)),
                ('cc_addr', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('is_auto_reply', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actual_sender', models.ForeignKey(blank=True, help_text='内部实际发件人。对外身份由 mailbox 决定。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='accounts.mailbox')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'db_table': 'messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('mime', models.CharField(blank=True, max_length=200)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('path', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.message')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'db_table': 'attachments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('normalized_subject', models.CharField(db_index=True, help_text='剥离 Re:/Fwd:/工单号后的纯净主题。', max_length=500)),
                ('status', models.CharField(choices=[('open', '进行中'), ('pending', '等待客户'), ('closed', '已关闭')], default='open', max_length=20)),
                ('is_awaiting_reply', models.BooleanField(db_index=True, default=False, help_text='待回复标签。客户来信置 True，外发回复置 False。')),
                ('customer_email', models.EmailField(db_index=True, max_length=254)),
                ('last_message_at', models.DateTimeField(db_index=True, help_text='最后一条消息时间。用于粘性判断和列表排序。')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, help_text='认领人。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='当前归属组。', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='accounts.group')),
                ('mailbox', models.ForeignKey(help_text='入口邮箱。', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='accounts.mailbox')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'db_table': 'tickets',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['group', 'is_awaiting_reply'], name='ticket_group_awaiting_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['customer_email', 'last_message_at'], name='ticket_cust_last_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['ticket', 'created_at'], name='msg_ticket_created_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_id'], name='msg_message_id_idx'),
        ),
    ]
