# Generated by Django 5.2.17 on 2026-09-25 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('slate', '灰'), ('blue', '蓝'), ('green', '绿'), ('amber', '黄'), ('red', '红'), ('purple', '紫'), ('teal', '青')], default='slate', help_text='界面角标配色。', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, help_text='为空表示全局标签（所有组可用）；否则为该组专属标签。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='accounts.group')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tags',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TicketTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('rule', '规则自动'), ('manual', '人工添加')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='人工添加时的操作人；规则添加为空。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_ticket_tags', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tags', to='tickets.tag')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tags', to='tickets.ticket')),
            ],
            options={
                'verbose_name': '工单标签',
                'verbose_name_plural': '工单标签',
                'db_table': 'ticket_tags',
                'ordering': ['tag__name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_tag_per_group'),
        ),
        migrations.AddConstraint(
            model_name='tickettag',
            constraint=models.UniqueConstraint(fields=('ticket', 'tag'), name='unique_ticket_tag'),
        ),
    ]
