# Generated by Django 5.2.17 on 2026-09-26 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='服务端生成的随机 ntfy topic。全局唯一，防止串频道。', max_length=64, unique=True)),
                ('server', models.CharField(blank=True, help_text='注册当时的 ntfy 实例地址（冗余记录，便于排查换域名后旧订阅失效）。', max_length=255)),
                ('device_label', models.CharField(blank=True, help_text='便于用户在设置里辨认并吊销，例如「Pixel 7 · 小邱」。', max_length=64)),
                ('enabled', models.BooleanField(default=True, help_text='关闭后后端不再向该设备发布。')),
                ('dnd_start', models.TimeField(blank=True, help_text='免打扰开始时刻。与 dnd_end 都非空才视为启用。', null=True)),
                ('dnd_end', models.TimeField(blank=True, help_text='免打扰结束时刻。', null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='最后一次续订（E3）时间。用于判断「这台设备还活着吗」。', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='归属用户。用户被删除时订阅一并消失。', on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '推送订阅',
                'verbose_name_plural': '推送订阅',
                'db_table': 'push_subscriptions',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'enabled'], name='push_sub_user_enabled_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'topic'), name='uniq_subscription_user_topic')],
            },
        ),
    ]
